blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/ArtisanPack-UI/livewire-ui-components/wiki/home
    about: Check our documentation before opening an issue
