<?php

declare(strict_types=1);
/**
 * Generate IDE Helper Command
 *
 * Artisan command to generate IDE helper file for component autocompletion.
 *
 * @author     Jacob Martella
 * @copyright  2026 Jacob Martella
 * @license    MIT
 *
 * @link       https://gitlab.com/jacob-martella-web-design/artisanpack-ui/livewire-ui-components
 * @since      1.0.0
 */

namespace ArtisanPack\LivewireUiComponents\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

/**
 * Generates a Blade file that provides component aliases for IDE autocompletion.
 *
 * @since 1.0.0
 */
class GenerateIdeHelperCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'artisanpack:generate-ide-helper';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate IDE helper file for ArtisanPack UI component autocompletion.';

    /**
     * Execute the console command.
     *
     * @since 1.0.0
     */
    public function handle(): int
    {
        $this->info('Generating IDE helper file for ArtisanPack UI components...');

        $prefix          = config('artisanpack.livewire-ui-components.prefix', 'artisanpack');
        $bladeComponents = config('artisanpack.livewire-ui-components.components', []);
        $filePath        = base_path('_ide_helper_artisanpack.blade.php');

        $content = "<?php\n/**\n * This file is generated automatically by the `artisanpack:generate-ide-helper` command.\n * Do not edit this file manually. It should be added to your .gitignore.\n */\n\n// @formatter:off\n?>\n\n";

        foreach (array_keys($bladeComponents) as $alias) {
            $content .= "@component('{$prefix}-{$alias}') @endcomponent\n";
        }

        File::put($filePath, $content);

        $this->info("Helper file generated successfully at: {$filePath}");

        return self::SUCCESS;
    }
}
